### PR TITLE
TDRD-217 Pass empty values & filter out protected properties

### PR DESCRIPTION
**Pull request by thanhz**
Pass empty values so that they can be handled correctly in the api & filter out protected properties from the input.
https://github.com/nationalarchives/tdr-consignment-api/pull/876

### CODE REVIEW

**Comment by thanhz** [comment]
I tried to write some unit test for these changes but can't see a way to do it :disappointed: 
The api also checks if there are protected properties in the input which has been tested.

**Review by vimleshtna — COMMENTED** [review]
Looks good to me. Just add a unit test to verify the graphql request data. Thanks
Also, remove the `propertyProtected` property from the customMetadata.json

**Comment by thanhz** [comment]
> Looks good to me. Just add a unit test to verify the graphql request data. Thanks Also, remove the `propertyProtected` property from the customMetadata.json

I've extracted out the logic to a new utils object and added the unit test

**Review by vimleshtna — DISMISSED** [review]
Looks good. Thanks

**Comment by thanhz** [comment]
Will merge when the `TDR Deploy Draft Metadata Validator Lambda` is fixed

**Review by vimleshtna — APPROVED** [review]

**Pull request merged**
